os: linux
dist: focal
language: python

stages:
- lint
- test

jobs:
  include:
  - stage: lint
    env: TOXENV=lint

python:
- 3.6
- 3.7
- 3.8
- 3.9

install:
- pip install "setuptools>=36.3" tox codecov

script:
- tox

after_success:
- codecov
